### ISSUE TITLE
OpenSearch-Benchmark Example Command Gives Error [BUG]

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark#106]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.
- Download OpenSearch-Benchmark via pip3 install opensearch-benchmark
- Run the following command:`opensearch-benchmark execute_test --distribution-version=1.0.0 --workload=http_logs --test-mode `
```
   ____                  _____                      __       ____                  __                         __
  / __ \____  ___  ____ / ___/___  ____ ___________/ /_     / __ )___  ____  _____/ /_  ____ ___  ____ ______/ /__
 / / / / __ \/ _ \/ __ \\__ \/ _ \/ __ `/ ___/ ___/ __ \   / __  / _ \/ __ \/ ___/ __ \/ __ `__ \/ __ `/ ___/ //_/
/ /_/ / /_/ /  __/ / / /__/ /  __/ /_/ / /  / /__/ / / /  / /_/ /  __/ / / / /__/ / / / / / / / / /_/ / /  / ,<
\____/ .___/\___/_/ /_/____/\___/\__,_/_/   \___/_/ /_/  /_____/\___/_/ /_/\___/_/ /_/_/ /_/ /_/\__,_/_/  /_/|_|
    /_/

[ERROR] Cannot execute_test. Error in builder ([Errno 2] No such file or directory: '/home/ec2-user/.benchmark/benchmarks/workloads/default/http_logs/test_procedures/common/opensearch-benchmark-provisionconfigs')
```

**Expected behavior**
It should print out the test-mode report. It requires accessing the opensearch-benchmark-provisionconfigs directory within the opensearch-benchmark repository. Two ways to get pass this is either following the setup in the DEVELOPER_GUIDE.md or cloning the repository and cd-ing into that repository and running the opensearch-benchmark command once more. 

**Logs**
https://pastebin.pl/view/2045f7d8

**More Context (please complete the following information):**
- Workload = any workload (i.e. geonames or http_logs)
- Service = OpenSearch
- Version = OpenSearch-Benchmark 1.0.0

**Comment by dtaivpp** [comment]
I am also receiving this issue. I was using Ubuntu 20.04, Python 3.8.10

**Comment by travisbenedict** [comment]
Hey @BlackMetalz thanks for your interest in OpenSearch Benchmark!

We're currently working on some documentation that should help clear up some of this. I've also posted a response to your question on https://github.com/opensearch-project/OpenSearch/issues/2461. 

The command mentioned in this issue is just a sort of quickstart sanity test command. To really do accurate benchmarking for OpenSearch we'd recommend running OpenSearch on a separate host from where you're using Benchmark since the resource utilization for Benchmark could affect the OpenSearch cluster. 

Once you have your OpenSearch cluster provisioned you can run Benchmark using the `--pipeline=benchmark-only` parameter and supplying the endpoint to your cluster using `--target-hosts=<cluster_endpoint>`. Some basic example commands can be found below:


Clusters with security plugin disabled:
`opensearch-benchmark execute_test --pipeline=benchmark-only --workload=nyc_taxis --target-hosts=<cluster_endpoint>`

Clusters with security plugin enabled:
`opensearch-benchmark execute_test --pipeline=benchmark-only --workload=nyc_taxis --target-hosts=<cluster_endpoint> --client-options=basic_auth_user:'admin',basic_auth_password:'admin!a',verify_certs:false,use_ssl:true`


----------

If you want to run this specific command the current workaround as suggested by @IanHoang is to
1. Clone this repository
2. `cd` into it
3. Run `opensearch-benchmark execute_test --distribution-version=1.0.0 --workload=http_logs --test-mode`

**Comment by BlackMetalz** [comment]
> Hey @BlackMetalz thanks for your interest in OpenSearch Benchmark!
> 
> We're currently working on some documentation that should help clear up some of this. I've also posted a response to your question on [opensearch-project/OpenSearch#2461](https://github.com/opensearch-project/OpenSearch/issues/2461).
> 
> The command mentioned in this issue is just a sort of quickstart sanity test command. To really do accurate benchmarking for OpenSearch we'd recommend running OpenSearch on a separate host from where you're using Benchmark since the resource utilization for Benchmark could affect the OpenSearch cluster.
> 
> Once you have your OpenSearch cluster provisioned you can run Benchmark using the `--pipeline=benchmark-only` parameter and supplying the endpoint to your cluster using `--target-hosts=<cluster_endpoint>`. Some basic example commands can be found below:
> 
> Clusters with security plugin disabled: `opensearch-benchmark execute_test --pipeline=benchmark-only --workload=nyc_taxis --target-hosts=<cluster_endpoint>`
> 
> Clusters with security plugin enabled: `opensearch-benchmark execute_test --pipeline=benchmark-only --workload=nyc_taxis --target-hosts=<cluster_endpoint> --client-options=basic_auth_user:'admin',basic_auth_password:'admin!a',verify_certs:false,use_ssl:true`
> 
> If you want to run this specific command the current workaround as suggested by @IanHoang is to
> 
> 1. Clone this repository
> 2. `cd` into it
> 3. Run `opensearch-benchmark execute_test --distribution-version=1.0.0 --workload=http_logs --test-mode`

Thanks for reply, i cloned the repo, but where is the file `opensearch-benchmark` :(

**Comment by travisbenedict** [comment]
Have you installed OpenSearch Benchmark?  `pip3 install opensearch-benchmark`

More information here: https://github.com/opensearch-project/OpenSearch-Benchmark#installing-benchmark
