### ISSUE TITLE
Remote Cluster Support needed for Amazon Managed OpenSearch Service

### ISSUE THREAD

**Issue by GuanLinZhang** [opensearch-project/opensearch-benchmark#204]
Currently, I'm working on a project for benchmarking the managed OpenSearch cluster. 

Since Rally is not compatible for cluster with OSS license, and cannot find related docs or check guide on opensearch-benchmark -h. I suppose the remote cluster is not supported yes.

Please provide some suggestions about how to run benchmark on remote cluster if any.

Thanks in advance

**Comment by travisbenedict** [comment]
Hi @GuanLinZhang thanks for your interest in OpenSearch Benchmark.

There's some documentation and examples here that should be able to help you - https://github.com/opensearch-project/opensearch-benchmark/blob/main/docs/api/execute-test.md#common-arguments

In short you should be able to use the `--pipeline benchmark-only` argument to test against a remote cluster. Something like this command should be able to fit your use case.
```
opensearch-benchmark execute_test --workload nyc_taxis --pipeline benchmark-only --target-hosts <endpoint> --client-options "basic_auth_user:<username>,basic_auth_password:<password>"
```


Note that if you're using Amazon OpenSearch Service you won't be able to use IAM based authentication for the test cluster since OpenSearch Benchmark does not yet support SigV4 signing. We're tracking SigV4 support in this issue: https://github.com/opensearch-project/opensearch-benchmark/issues/158

**Comment by GuanLinZhang** [comment]
Hi @travisbenedict That's really helpful.

I think it would be better if we could put the common arguments into the frontpage : )

Close this issue.
