### ISSUE TITLE
[BUG] Inconsistent formatting of subcommands (e.g., "execute_test" vs "create-workload")

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/opensearch-benchmark#238]
**Describe the bug**
Subcommands should be consistent in syntax. In this case, it looks like we replaced "race" with "execute_test," but the underscore should be a hyphen because a hyphen is used for "create-workload" (previously "create-track").

This can be confusing for users, especially if they're writing scripts for OSB automation and use a hyphen by habit.

**To Reproduce**
N/A

**Expected behavior**
All subcommands should follow the same formatting style. In this case, I believe that `execute_test` should be changed to `execute-test`.

**Logs**
N/A

**More Context (please complete the following information):**
- Workload N/A
- Service N/A
- Version 0.2.0

**Additional context**
N/A just the formatting issue. You might want to also check with product leads because I don't think that `execute-test` is the preferred verb for inclusive language. Probably something along the lines of `run-test` would work better.

**Comment by IanHoang** [comment]
Thanks for bringing this to our attention. Before updating subcommand action `execute_test` format to `execute-test`, we should confirm if should replace it with another action -- `run`, `run-test`, etc. -- as you suggested above.

At the time of the fork in 2021, legal team proposed to substitute `execute-test` with subcommand `race` since another subcomponent throughout the code base named `Race` (referring to the race object rather than action) was replaced with `TestExecution`. If the action `execute-test` is changed, we would need to update `TestExecution` as well.

**Comment by IanHoang** [comment]
Removed the bug tag on this since doesn't break OSB

**Comment by IanHoang** [comment]
Closing this since merged in.
