### ISSUE TITLE
Enhance SigV4 support to handle role-based credentials 

### ISSUE THREAD

**Issue by gkamat** [opensearch-project/opensearch-benchmark#377]
**Is your feature request related to a problem? Please describe.**

SigV4 support was added in [this PR](https://github.com/opensearch-project/opensearch-benchmark/issues/158).  However, it supports only user-based credentials and not role-based ones; the latter have a session token.  

Adding this capability will permit using SigV4 authentication without the need of creating a user with permanent credentials.

**Comment by cgchinmay** [comment]
@IanHoang  Hi, I would like to work on this issue. I did see this [PR](https://github.com/opensearch-project/opensearch-benchmark/pull/329) but can you confirm that it does not support role-based access with session token yet ?

**Comment by beaioun** [comment]
@IanHoang @cgchinmay Hi, I would also like to contribute to this issue if you are open to collaboration. I am thinking this issue is essentially to supplying the session token to the request header, or in this case botocore.credentials.Credentials class. And maybe adding some features such as STS token generation, and explaining IAM role permissions in the benchmark docs along the way for users that don't know how to generate session tokens. Hope we can work together!

**Comment by cgchinmay** [comment]
@beaioun I had the code ready and was about to send a PR but can definitely use help with testing it out. Lets discuss this later today or on slack with @IanHoang for collaboration
